#!/bin/zsh

y=$(system_profiler SPPowerDataType | grep -E "Connected|State")
used_memory=$(neofetch memory| sed 's/^.*: //; s/ //g;s/8192MiB.*$/8192MiB/')

charging_state=$(echo "${y##* }" | sed 's/Yes/⚡️/; s/No/🔋/')
charging_percentage=$(echo "${y:31:3 }%")

echo "💾 $used_memory $charging_state $charging_percentage"
