#!/bin/zsh

y=$(system_profiler SPPowerDataType)
# getting memory data from neofetch source code
hw_pagesize="$(sysctl -n hw.pagesize)"
mem_total="$(($(sysctl -n hw.memsize) / 1024 / 1024))"
pages_app="$(($(sysctl -n vm.page_pageable_internal_count) - $(sysctl -n vm.page_purgeable_count)))"
pages_wired="$(vm_stat | awk '/ wired/ { print $4 }')"
pages_compressed="$(vm_stat | awk '/ occupied/ { printf $5 }')"
pages_compressed="${pages_compressed:-0}"

echo "$(((${pages_app} + ${pages_wired//.} + ${pages_compressed//.}) * hw_pagesize / 1024 / 1024))MiB/${mem_total}Mib  $(echo "${$(echo $y | grep Connected)##* }" | sed 's/Yes/⚡️/; s/No/  /') ${$(echo $y | grep State)##* }%"
